In [57]:
print("Columns Trnasformer")

Columns Trnasformer

In [58]:
import numpy as np
import pandas as pd

In [59]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [60]:
df = pd.read_csv('covid_toy.csv')

In [61]:
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [62]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [63]:
from sklearn.model_selection import train_test_split

In [64]:
X_train , X_test , Y_train ,Y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'] , test_size=0.2)

# Step 1

In [65]:
si = SimpleImputer()

In [66]:
X_train_fever = si.fit_transform(X_train[['fever']])

X_test_fever = si.fit_transform(X_test[['fever']])

In [67]:
X_train_fever.shape

(80, 1)

In [68]:
# OrdinalEncoder --> cough

oe = OrdinalEncoder(categories=[['Mild','Strong']])

X_trian_cough = oe.fit_transform(X_train[['cough']])

X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [71]:
# OneHot Encoder --> Gender , City

ohe = OneHotEncoder(sparse_output=False , drop='first')

X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [72]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [73]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

# Usign Columns Transformer

In [78]:
df = pd.read_csv('tips.csv')
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [79]:
x_train , x_trest , y_train , y_test = train_test_split(df.drop(columns=['total_bill']) , df['total_bill'] ,test_size=0.2)

In [80]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [76]:
from sklearn.compose import ColumnTransformer

In [81]:
transformer = ColumnTransformer(transformers=[
    ('tnf1', OneHotEncoder(sparse_output=False , drop='first'),['sex','smoker','day','time'])
])


# ('Transformer_Name' , 'transformer_opt()' , 'list_of_columns_name')

In [82]:
transformer.fit_transform(x_train).shape

(195, 6)

In [ ]:
# OneHotEncoder --> No Order
# LabelEncoder / OrdinalEncoder -->(Order hota hai)
#