In [1]:
print("Day 2 of data dividation / split / x_train , x_test , y_train , y_test  data  In Details")

Day 2 of data dividation / split / x_train , x_test , y_train , y_test  data  In Details

In [2]:
import numpy as np 
import pandas as pd

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
d = pd.read_csv("placement.csv")
d.head(4)

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1

In [5]:
x =d.drop(['placed'], axis=1 )
x

    cgpa  resume_score
0   8.14          6.52
1   6.17          5.17
2   8.27          8.86
3   6.88          7.27
4   7.52          7.30
..   ...           ...
95  6.33          6.38
96  8.23          7.76
97  6.65          7.78
98  8.14          5.63
99  6.09          6.61

[100 rows x 2 columns]

In [6]:
y = d['placed']
y

0     1
1     0
2     1
3     1
4     1
     ..
95    0
96    1
97    0
98    1
99    0
Name: placed, Length: 100, dtype: int64

In [7]:
x_train , x_test , y_train , y_test = train_test_split(x,y ,test_size=0.2,  random_state=42 , )

In [8]:
print("d Data Shape :",d.shape)
print("x_train data Shape: ",x_train.shape)
print("x_test data Shape: ",x_test.shape)
print("----------------------------")
print("y Data Shape: ",y.shape)
print("y_train Data Shape: ",y_train.shape)
print("y_test Data Shape: ",y_test.shape)

d Data Shape : (100, 3)
x_train data Shape:  (80, 2)
x_test data Shape:  (20, 2)
----------------------------
y Data Shape:  (100,)
y_train Data Shape:  (80,)
y_test Data Shape:  (20,)

Day 2 Start's Here

In [9]:
print("Day2 Starts Here")

Day2 Starts Here

In [10]:
import numpy as np 
import pandas as pd

In [11]:
df = pd.read_csv("covid_toy.csv")

In [12]:
x = df.drop(columns='has_covid')
y = df['has_covid']

In [13]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
df['cough'] = df['cough'].map({"Mild":0,"Strong":1})
df['gender'] = df['gender'].map({"Female":0,"Male":1})
df['has_covid'] = df['has_covid'].map({"No":0,"Yes":1})
df['city'] = df['city'].map({"Kolkata":0,"Delhi":1,"Mumbai":2,"Bangalore":3})

In [15]:
df.head(2)

   age  gender  fever  cough  city  has_covid
0   60       1  103.0      0     0          0
1   27       1  100.0      0     1          1

In [ ]:
np.round(x_train.describe(),2)

         age   fever
count  80.00   71.00
mean   42.91  101.00
std    24.47    2.05
min     5.00   98.00
25%    20.00   99.50
50%    42.00  101.00
75%    65.00  103.00
max    84.00  104.00

In [17]:
from sklearn.preprocessing import StandardScaler

In [20]:
sc = StandardScaler()

In [29]:
x_train_sc = sc.fit_transform(x_train) ### Fit Means Learn the paramerters transform means apply on that

In [30]:
x_train_new = pd.DataFrame(x_train_sc,columns=x_train.columns)

In [31]:
np.round(x_train_new.describe())

        age  gender  fever  cough  city
count  80.0    80.0   71.0   80.0  80.0
mean   -0.0     0.0   -0.0   -0.0   0.0
std     1.0     1.0    1.0    1.0   1.0
min    -2.0    -1.0   -1.0   -1.0  -1.0
25%    -1.0    -1.0   -1.0   -1.0  -1.0
50%    -0.0    -1.0    0.0   -1.0   0.0
75%     1.0     1.0    1.0    1.0   1.0
max     2.0     1.0    1.0    1.0   1.0

Praticeeeees

In [23]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [24]:
df = pd.read_csv("covid_toy.csv")
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [25]:
df['cough'] = df['cough'].map({"Mild":0,"Strong":1})
df['gender'] = df['gender'].map({"Female":0,"Male":1})
df['has_covid'] = df['has_covid'].map({"No":0,"Yes":1})
df['city'] = df['city'].map({"Kolkata":0,"Delhi":1,"Mumbai":2,"Bangalore":3})

In [26]:
x = df.drop(columns='has_covid')
y = df['has_covid']

In [27]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [28]:
sc = StandardScaler()

In [ ]:
x_train_sc = sc.fit_transform(x_train)
# x_test_sc = sc.transform(x_test)

In [ ]:
x_train_new = pd.DataFrame(x_train_sc,columns=x_train.columns)
x_test_new = pd.DataFrame(x_test_sc,columns=x_test.columns)