In [78]:
print("Day 4")

Day 4

In [5]:
import numpy as np 
import pandas as pd

In [6]:
df = pd.read_csv("covid_toy.csv")

In [7]:
df['cough'] = df['cough'].map({"Mild":0,"Strong":1})
df['gender'] = df['gender'].map({"Male":0,"Female":1})
df['has_covid'] = df['has_covid'].map({"No":0,"Yes":1})
df['city'] = df['city'].map({"Kolkata":0,"Delhi":1,"Mumbai":2,"Bangalore":3})

In [8]:
x = df.drop(columns=['has_covid'])
y = df['has_covid']

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [12]:
np.round(x_train.describe(),2)

         age  gender   fever  cough   city
count  80.00   80.00   71.00  80.00  80.00
mean   42.91    0.59  101.00   0.40   1.56
std    24.47    0.50    2.05   0.49   1.23
min     5.00    0.00   98.00   0.00   0.00
25%    20.00    0.00   99.50   0.00   0.00
50%    42.00    1.00  101.00   0.00   2.00
75%    65.00    1.00  103.00   1.00   3.00
max    84.00    1.00  104.00   1.00   3.00

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
sc = StandardScaler()

In [15]:
x_train_sc = sc.fit_transform(x_train)

In [16]:
x_train_new = pd.DataFrame(x_train_sc , columns= x_train.columns)

In [17]:
np.round(x_train_new.describe(),2)

         age  gender  fever  cough   city
count  80.00   80.00  71.00  80.00  80.00
mean   -0.00   -0.00  -0.00  -0.00   0.00
std     1.01    1.01   1.01   1.01   1.01
min    -1.56   -1.19  -1.47  -0.82  -1.28
25%    -0.94   -1.19  -0.74  -0.82  -1.28
50%    -0.04    0.84   0.00  -0.82   0.36
75%     0.91    0.84   0.98   1.22   1.18
max     1.69    0.84   1.47   1.22   1.18