In [1]:
print("Day6")

Day6

# Encoading

Encoading --> Transform Your Categorical Data Into Numerical Data

(1) LabelEncoder  has_covid['Yes' , 'No'] -- Value_counts() --> Encode --> has_covid[1,0]

In [3]:
import numpy as np
import pandas as pd

In [4]:

df =pd.read_csv("covid_toy.csv")

In [5]:
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [7]:
df=df.dropna()

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
lb = LabelEncoder()

In [11]:
df['gender'] = lb.fit_transform(df['gender'])
df['cough'] = lb.fit_transform(df['cough'])
df['city'] = lb.fit_transform(df['city'])
df['has_covid'] = lb.fit_transform(df['has_covid'])

In [13]:
x = df.drop(columns=['has_covid'])
y =df['has_covid']

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state=42)

# Apply Standardization For Converting My Data into Normal Distribution

In [21]:
from sklearn.preprocessing import StandardScaler

In [22]:
sc = StandardScaler()

In [23]:
x_train_sc = sc.fit_transform(x_train)

In [24]:
x_train_new = pd.DataFrame(x_train_sc , columns = x_train.columns)

In [26]:
np.round(x_train_new.describe(),2)

         age  gender  fever  cough   city
count  72.00   72.00  72.00  72.00  72.00
mean   -0.00   -0.00  -0.00   0.00   0.00
std     1.01    1.01   1.01   1.01   1.01
min    -1.53   -0.75  -1.30  -0.73  -1.20
25%    -0.95   -0.75  -0.83  -0.73  -1.20
50%     0.14   -0.75   0.13  -0.73  -0.24
75%     0.86    1.33   0.72   1.37   0.72
max     1.57    1.33   1.55   1.37   1.69

# Tips Data Set

In [28]:
df = pd.read_csv("tips.csv")

In [30]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [35]:
from sklearn.preprocessing import LabelEncoder

In [36]:
lb = LabelEncoder()

In [37]:
df['sex'] = lb.fit_transform(df['sex'])
df['smoker'] = lb.fit_transform(df['smoker'])
df['day'] = lb.fit_transform(df['day'])
df['time'] = lb.fit_transform(df['time'])

In [40]:
x = df.drop(columns = ['total_bill'])
y =df['total_bill']

In [41]:
x_train , x_test , y_train , y_test = train_test_split(x,y, test_size = 0.2 , random_state=42)

In [42]:
# Apply Normalization

In [43]:
from sklearn.preprocessing import MinMaxScaler

In [44]:
mn  = MinMaxScaler()

In [48]:
x_train_mn = mn.fit_transform(x_train)

In [49]:
x_train_new = pd.DataFrame(x_train_mn , columns=x_train.columns)

In [50]:
np.round(x_train_new.describe(),2)

          tip     sex  smoker     day    time    size
count  195.00  195.00  195.00  195.00  195.00  195.00
mean     0.23    0.65    0.38    0.57    0.27    0.31
std      0.16    0.48    0.49    0.31    0.45    0.19
min      0.00    0.00    0.00    0.00    0.00    0.00
25%      0.11    0.00    0.00    0.33    0.00    0.20
50%      0.22    1.00    0.00    0.67    0.00    0.20
75%      0.30    1.00    1.00    0.67    1.00    0.40
max      1.00    1.00    1.00    1.00    1.00    1.00

# Insurance DataSet

In [51]:
df = pd.read_csv('insurance.csv')

In [54]:
df = df.dropna()

In [55]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [57]:
from sklearn.preprocessing import LabelEncoder

In [58]:
lb = LabelEncoder()

In [60]:
df['sex'] = lb.fit_transform(df['sex'])
df['smoker'] = lb.fit_transform(df['smoker'])
df['region'] = lb.fit_transform(df['region'])

In [61]:
df

      age  sex     bmi  children  smoker  region      charges
0      19    0  27.900         0       1       3  16884.92400
1      18    1  33.770         1       0       2   1725.55230
2      28    1  33.000         3       0       2   4449.46200
3      33    1  22.705         0       0       1  21984.47061
4      32    1  28.880         0       0       1   3866.85520
...   ...  ...     ...       ...     ...     ...          ...
1333   50    1  30.970         3       0       1  10600.54830
1334   18    0  31.920         0       0       0   2205.98080
1335   18    0  36.850         0       0       2   1629.83350
1336   21    0  25.800         0       0       3   2007.94500
1337   61    0  29.070         0       1       1  29141.36030

[1338 rows x 7 columns]

In [63]:
x = df.drop(columns = ['charges'])
y =df['charges']

In [66]:
from sklearn.model_selection import train_test_split

In [67]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size =0.2 , random_state=42)

In [68]:
from sklearn.preprocessing import StandardScaler

In [70]:
sc = StandardScaler()

In [71]:
x_train_sc = sc.fit_transform(x_train)

In [72]:
x_train_new = pd.DataFrame(x_train_sc , columns = x_train.columns)

In [73]:
np.round(x_train_new.describe(),2)

           age      sex      bmi  children   smoker   region
count  1070.00  1070.00  1070.00   1070.00  1070.00  1070.00
mean     -0.00    -0.00    -0.00     -0.00     0.00    -0.00
std       1.00     1.00     1.00      1.00     1.00     1.00
min      -1.52    -1.02    -2.42     -0.91    -0.51    -1.35
25%      -0.88    -1.02    -0.72     -0.91    -0.51    -0.46
50%       0.01     0.98    -0.06     -0.09    -0.51     0.44
75%       0.83     0.98     0.65      0.73    -0.51     0.44
max       1.75     0.98     3.74      3.20     1.97     1.34