In [26]:
print("Day 7 ")

Day 7

In [27]:
import numpy as np
import pandas as pd

In [28]:
df = pd.read_csv("covid_toy.csv")
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [29]:
from sklearn.preprocessing import LabelEncoder

In [30]:
lb = LabelEncoder()

In [32]:
df['gender'] = lb.fit_transform(df['gender'])
df['cough'] = lb.fit_transform(df['cough'])
df['city'] = lb.fit_transform(df['city'])
df['has_covid'] = lb.fit_transform(df['has_covid'])

In [33]:
x = df.drop(columns='has_covid')
y =df['has_covid']

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state=42)

In [36]:
from sklearn.preprocessing import StandardScaler

In [37]:
sc = StandardScaler()

In [38]:
x_train_sc = sc.fit_transform(x_train)

In [39]:
x_train_new= pd.DataFrame(x_train_sc , columns= x_train.columns)

In [40]:
np.round(x_train_new.describe(),2)

         age  gender  fever  cough   city
count  80.00   80.00  71.00  80.00  80.00
mean   -0.00    0.00  -0.00  -0.00  -0.00
std     1.01    1.01   1.01   1.01   1.01
min    -1.56   -0.84  -1.47  -0.82  -1.17
25%    -0.94   -0.84  -0.74  -0.82  -1.17
50%    -0.04   -0.84   0.00  -0.82  -0.27
75%     0.91    1.19   0.98   1.22   0.63
max     1.69    1.19   1.47   1.22   1.53

In [41]:
from sklearn.preprocessing import MinMaxScaler

In [42]:
mn = MinMaxScaler()

In [43]:
x_train_mn = mn.fit_transform(x_train)

In [46]:
x_train_new2 = pd.DataFrame(x_train_mn , columns=x_train.columns)

In [47]:
np.round(x_train_new2.describe(),2)

         age  gender  fever  cough   city
count  80.00   80.00  71.00  80.00  80.00
mean    0.48    0.41   0.50   0.40   0.43
std     0.31    0.50   0.34   0.49   0.37
min     0.00    0.00   0.00   0.00   0.00
25%     0.19    0.00   0.25   0.00   0.00
50%     0.47    0.00   0.50   0.00   0.33
75%     0.76    1.00   0.83   1.00   0.67
max     1.00    1.00   1.00   1.00   1.00