In [102]:
print("Day 9")

Day 9

# Encoading 3 ::: --> Get_dummies

columns --> has_covid['Yes','No'] --> When We Apply get_dummies --> 2 columns Create

In [103]:
import numpy as np 
import pandas as pd

In [104]:
df = pd.read_csv("insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [105]:
a = pd.get_dummies(df , columns=['sex','smoker','region'])
a

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,True,False,False,True,False,False,False,True
1,18,33.770,1,1725.55230,False,True,True,False,False,False,True,False
2,28,33.000,3,4449.46200,False,True,True,False,False,False,True,False
3,33,22.705,0,21984.47061,False,True,True,False,False,True,False,False
4,32,28.880,0,3866.85520,False,True,True,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,False,True,True,False,False,True,False,False
1334,18,31.920,0,2205.98080,True,False,True,False,True,False,False,False
1335,18,36.850,0,1629.83350,True,False,True,False,False,False,True,False
1336,21,25.800,0,2007.94500,True,False,True,False,False,False,False,True
1337,61,29.070,0,29141.36030,True,False,False,True,False,True,False,False

In [106]:
# if i Have Sub-Categories --> 1 column drop --> Data MultiConielity
# issue Solve
# Model ---> OverFittitng --->
# 1 Student --> 2 Days Exam --> Exam Paper --> Exam Clear
# But 3 days --> Question Answers ---> xxxx

In [107]:
b =pd.get_dummies(df,columns=['sex','region','smoker'],drop_first=True)

In [108]:
c = b.astype(int)
c

,age,bmi,children,charges,sex_male,region_northwest,region_southeast,region_southwest,smoker_yes
0,19,27,0,16884,0,0,0,1,1
1,18,33,1,1725,1,0,1,0,0
2,28,33,3,4449,1,0,1,0,0
3,33,22,0,21984,1,1,0,0,0
4,32,28,0,3866,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...
1333,50,30,3,10600,1,1,0,0,0
1334,18,31,0,2205,0,0,0,0,0
1335,18,36,0,1629,0,0,1,0,0
1336,21,25,0,2007,0,0,0,1,0
1337,61,29,0,29141,0,1,0,0,1

In [109]:
# Covid Data
# Entire Categorical Data 
# 1-1 Sub-Category Drop
# Encode

Entire Categorical Data

In [110]:
df =pd.read_csv("covid_toy.csv")
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [111]:
pd.get_dummies(df,columns=['gender','cough','city','has_covid'])

,age,fever,gender_Female,gender_Male,cough_Mild,cough_Strong,city_Bangalore,city_Delhi,city_Kolkata,city_Mumbai,has_covid_No,has_covid_Yes
0,60,103.0,False,True,True,False,False,False,True,False,True,False
1,27,100.0,False,True,True,False,False,True,False,False,False,True
2,42,101.0,False,True,True,False,False,True,False,False,True,False
3,31,98.0,True,False,True,False,False,False,True,False,True,False
4,65,101.0,True,False,True,False,False,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
95,12,104.0,True,False,True,False,True,False,False,False,True,False
96,51,101.0,True,False,False,True,False,False,True,False,False,True
97,20,101.0,True,False,True,False,True,False,False,False,True,False
98,5,98.0,True,False,False,True,False,False,False,True,True,False
99,10,98.0,True,False,False,True,False,False,True,False,False,True

In [112]:
# df = df.dropna

In [113]:
b = pd.get_dummies(df,columns=['gender','cough','city','has_covid'] ,drop_first=True)

In [114]:
b

,age,fever,gender_Male,cough_Strong,city_Delhi,city_Kolkata,city_Mumbai,has_covid_Yes
0,60,103.0,True,False,False,True,False,False
1,27,100.0,True,False,True,False,False,True
2,42,101.0,True,False,True,False,False,False
3,31,98.0,False,False,False,True,False,False
4,65,101.0,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...
95,12,104.0,False,False,False,False,False,False
96,51,101.0,False,True,False,True,False,True
97,20,101.0,False,False,False,False,False,False
98,5,98.0,False,True,False,False,True,False
99,10,98.0,False,True,False,True,False,True

# Encoder 4 --> OneHotEncoder -->

In [125]:
df = pd.read_csv("insurance.csv")
df.head(2)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523

In [126]:
from sklearn.preprocessing import OneHotEncoder

In [127]:
ohe = OneHotEncoder(drop='first',sparse_output=False , dtype=np.int32)

In [128]:
ohe.fit_transform(df[['sex','smoker' , 'region']])

array([[0, 1, 0, 0, 1],
       [1, 0, 0, 1, 0],
       [1, 0, 0, 1, 0],
       ...,
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 1, 1, 0, 0]], shape=(1338, 5), dtype=int32)