In [1]:
print("Cars_Data Pratice MinMaxScaling")

Cars_Data Pratice MinMaxScaling

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("cars.csv")

In [4]:
df.head(2)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC BSII,1992,50000,100000,Petrol,Individual,Manual,Fourth & Above Owner
1,Maruti Gypsy E MG410W ST,1995,95000,100000,Petrol,Individual,Manual,Second Owner

In [5]:
df.drop(columns= ['name'] , inplace=True)

In [6]:
df['owner'] = df['owner'].map({"First Owner":0 , "Second Owner":1 , "Third Owner":2 , "Fourth & Above Owner":3 , "Test Drive Car":4 })
df['transmission'] = df['transmission'].map({"Manual":0 , "Automatic":1 })
df['seller_type'] = df['seller_type'].map({"Individual":0 , "Dealer":1 ,"Trustmark Dealer":2})
df['fuel'] = df['fuel'].map({"fuel":0 , "Diesel":1 ,"Petrol":2 , "CNG":3 , "LPG":4 , "Electric":5})

In [7]:
df

      year  selling_price  km_driven  fuel  seller_type  transmission  owner
0     1992          50000     100000     2            0             0      3
1     1995          95000     100000     2            0             0      1
2     1996         250000      35000     1            0             0      1
3     1996         200000      60000     1            0             0      0
4     1997         150000     120000     1            0             0      2
...    ...            ...        ...   ...          ...           ...    ...
4335  2020        1050000       1100     2            0             0      0
4336  2020         545000       5000     2            0             0      0
4337  2020         530000      45000     1            1             0      0
4338  2020         426000       1000     1            0             0      0
4339  2020         614000       1000     2            0             0      0

[4340 rows x 7 columns]

In [8]:
x = df.drop(columns='selling_price')
y = df['selling_price']

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train , x_test , y_train , y_test = train_test_split(x,y ,test_size=0.2 , random_state=42)

In [11]:
np.round(x_train.describe(),2)

          year  km_driven     fuel  seller_type  transmission    owner
count  3472.00    3472.00  3472.00      3472.00        3472.0  3472.00
mean   2013.13   66808.46     1.52         0.28           0.1     0.46
std       4.18   47571.73     0.55         0.50           0.3     0.73
min    1992.00       1.00     1.00         0.00           0.0     0.00
25%    2011.00   35000.00     1.00         0.00           0.0     0.00
50%    2014.00   60000.00     1.00         0.00           0.0     0.00
75%    2016.00   90000.00     2.00         1.00           0.0     1.00
max    2020.00  806599.00     5.00         2.00           1.0     4.00

In [12]:
from sklearn.preprocessing import MinMaxScaler

In [13]:
mn = MinMaxScaler()

In [14]:
x_train_mn = mn.fit_transform(x_train)

In [15]:
x_train_new = pd.DataFrame(x_train_mn, columns= x_train.columns)

In [16]:
np.round(x_train_new.describe(),2)

          year  km_driven     fuel  seller_type  transmission    owner
count  3472.00    3472.00  3472.00      3472.00        3472.0  3472.00
mean      0.75       0.08     0.13         0.14           0.1     0.11
std       0.15       0.06     0.14         0.25           0.3     0.18
min       0.00       0.00     0.00         0.00           0.0     0.00
25%       0.68       0.04     0.00         0.00           0.0     0.00
50%       0.79       0.07     0.00         0.00           0.0     0.00
75%       0.86       0.11     0.25         0.50           0.0     0.25
max       1.00       1.00     1.00         1.00           1.0     1.00