In [151]:
print("MinMaxScaling Pratice , Dataset =  Clicks.csv ")

MinMaxScaling Pratice , Dataset =  Clicks.csv

In [152]:
import numpy as np
import pandas as pd

In [153]:
df = pd.read_csv("click.csv")

In [154]:
df.head()

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Ad Topic Line,City,Gender,Country,Timestamp,Clicked on Ad
0,62.26,32.0,69481.85,172.83,Decentralized real-time circuit,Lisafort,Male,Svalbard & Jan Mayen Islands,2016-06-09 21:43:05,0
1,41.73,31.0,61840.26,207.17,Optional full-range projection,West Angelabury,Male,Singapore,2016-01-16 17:56:05,0
2,44.40,30.0,57877.15,172.83,Total 5thgeneration standardization,Reyesfurt,Female,Guadeloupe,2016-06-29 10:50:45,0
3,59.88,28.0,56180.93,207.17,Balanced empowering success,New Michael,Female,Zambia,2016-06-21 14:32:32,0
4,49.21,30.0,54324.73,201.58,Total 5thgeneration standardization,West Richard,Female,Qatar,2016-07-21 10:54:35,1

In [155]:
df.drop(columns=['Ad Topic Line'], inplace=True)
df.drop(columns=['City'] , inplace=True)
df.drop(columns=['Country'], inplace=True)
df.drop(columns=['Timestamp'],inplace=True)

In [156]:
df['Gender'] = df['Gender'].map({"Male":0 , "Female":1})

In [157]:
df

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Gender,Clicked on Ad
0,62.26,32.0,69481.85,172.83,0,0
1,41.73,31.0,61840.26,207.17,0,0
2,44.40,30.0,57877.15,172.83,1,0
3,59.88,28.0,56180.93,207.17,1,0
4,49.21,30.0,54324.73,201.58,1,1
...,...,...,...,...,...,...
9995,41.73,31.0,61840.26,207.17,0,1
9996,41.73,28.0,51501.38,120.49,0,0
9997,55.60,39.0,38067.08,124.44,1,0
9998,46.61,50.0,43974.49,123.13,1,1
9999,46.61,43.0,60575.99,198.45,0,1

In [158]:
x = df.drop(columns=['Area Income'])
y = df['Area Income']

In [159]:
from sklearn.model_selection import train_test_split

In [160]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state=42)

In [161]:
np.round(x_train.describe(),2)

,Daily Time Spent on Site,Age,Daily Internet Usage,Gender,Clicked on Ad
count,8000.00,8000.00,8000.00,8000.00,8000.00
mean,61.75,36.00,177.54,0.54,0.49
std,15.74,8.56,40.80,0.50,0.50
min,32.60,19.00,105.22,0.00,0.00
25%,48.86,29.00,140.15,0.00,0.00
50%,59.59,35.00,178.92,1.00,0.00
75%,76.81,42.00,212.38,1.00,1.00
max,90.97,60.00,269.96,1.00,1.00

In [162]:
from sklearn.preprocessing import MinMaxScaler

In [163]:
mn = MinMaxScaler()

In [164]:
x_train_mn = mn.fit_transform(x_train)

In [165]:
x_train_new = pd.DataFrame(x_train_mn , columns= x_train.columns)

In [166]:
np.round(x_train_new.describe(),2)

,Daily Time Spent on Site,Age,Daily Internet Usage,Gender,Clicked on Ad
count,8000.00,8000.00,8000.00,8000.00,8000.00
mean,0.50,0.41,0.44,0.54,0.49
std,0.27,0.21,0.25,0.50,0.50
min,0.00,0.00,0.00,0.00,0.00
25%,0.28,0.24,0.21,0.00,0.00
50%,0.46,0.39,0.45,1.00,0.00
75%,0.76,0.56,0.65,1.00,1.00
max,1.00,1.00,1.00,1.00,1.00