In [1]:
print("Project Work")

Project Work

In [2]:
import numpy as np 
import pandas as pd

# Task 1: Data Understanding & Cleaning

Load dataset, check shape, data types, missing values and duplicates.

In [3]:
# Load Data_Set

df = pd.read_csv("social_media_user_behavior.csv")
df.head(2)

,user_id,age,age_group,gender,country,occupation,education_level,income_bracket,relationship_status,primary_platform,...,productivity_impact,platform_satisfaction,account_created_date,account_age_years,is_verified_account,is_content_creator,uses_ai_features,daily_notifications,checks_phone_first_morning,uses_screen_time_limits
0,USR-000001,22,18-24,Non-Binary,Philippines,Teacher/Educator,Doctoral/Professional,$100K-$150K,Married,Facebook,...,No Change,Dissatisfied,2025-05-14,0.9,False,False,False,20,True,False
1,USR-000002,31,25-34,Prefer Not to Say,United Kingdom,Marketing Professional,High School or Below,$50K-$75K,In a Relationship,TikTok,...,No Change,Dissatisfied,2019-07-18,6.7,False,False,False,31,True,False

To Check The Shape(row , Columns)

In [4]:
df.shape

(25000, 45)

To Check Data Types

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 45 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   user_id                             25000 non-null  str
 1   age                                 25000 non-null  int64
 2   age_group                           25000 non-null  str
 3   gender                              25000 non-null  str
 4   country                             25000 non-null  str
 5   occupation                          25000 non-null  str
 6   education_level                     25000 non-null  str
 7   income_bracket                      25000 non-null  str
 8   relationship_status                 25000 non-null  str
 9   primary_platform                    25000 non-null  str
 10  num_platforms_used                  25000 non-null  int64
 11  daily_screen_time_minutes           25000 non-null  int64
 12  weekly_sessions                     25000 non-null  int64
 13  avg_session_duration_minutes        25000 non-null  float64
 14  preferred_content_type              25000 non-null  str
 15  primary_device                      25000 non-null  str
 16  usage_purpose                       25000 non-null  str
 17  posts_per_week                      25000 non-null  int64
 18  likes_per_day                       25000 non-null  int64
 19  comments_per_day                    25000 non-null  int64
 20  shares_per_week                     25000 non-null  int64
 21  followers_count                     25000 non-null  int64
 22  following_count                     25000 non-null  int64
 23  engagement_rate_pct                 25000 non-null  float64
 24  video_consumption_daily_minutes     25000 non-null  int64
 25  has_purchased_via_social            25000 non-null  bool
 26  follows_influencers                 25000 non-null  bool
 27  ad_click_frequency                  25000 non-null  str
 28  monthly_social_spending_usd         25000 non-null  float64
 29  uses_privacy_settings               25000 non-null  bool
 30  experienced_cyberbullying           25000 non-null  bool
 31  reports_fake_news_frequency         25000 non-null  str
 32  self_reported_mental_health_effect  25000 non-null  str
 33  sleep_hours_per_night               25000 non-null  float64
 34  addiction_level_1_to_10             25000 non-null  int64
 35  productivity_impact                 25000 non-null  str
 36  platform_satisfaction               25000 non-null  str
 37  account_created_date                25000 non-null  str
 38  account_age_years                   25000 non-null  float64
 39  is_verified_account                 25000 non-null  bool
 40  is_content_creator                  25000 non-null  bool
 41  uses_ai_features                    25000 non-null  bool
 42  daily_notifications                 25000 non-null  int64
 43  checks_phone_first_morning          25000 non-null  bool
 44  uses_screen_time_limits             25000 non-null  bool
dtypes: bool(9), float64(5), int64(13), str(18)
memory usage: 7.1 MB

Missing Values And Duplicates

In [6]:
df.isnull().sum()

user_id                               0
age                                   0
age_group                             0
gender                                0
country                               0
occupation                            0
education_level                       0
income_bracket                        0
relationship_status                   0
primary_platform                      0
num_platforms_used                    0
daily_screen_time_minutes             0
weekly_sessions                       0
avg_session_duration_minutes          0
preferred_content_type                0
primary_device                        0
usage_purpose                         0
posts_per_week                        0
likes_per_day                         0
comments_per_day                      0
shares_per_week                       0
followers_count                       0
following_count                       0
engagement_rate_pct                   0
video_consumption_daily_minutes       0
has_purchased_via_social              0
follows_influencers                   0
ad_click_frequency                    0
monthly_social_spending_usd           0
uses_privacy_settings                 0
experienced_cyberbullying             0
reports_fake_news_frequency           0
self_reported_mental_health_effect    0
sleep_hours_per_night                 0
addiction_level_1_to_10               0
productivity_impact                   0
platform_satisfaction                 0
account_created_date                  0
account_age_years                     0
is_verified_account                   0
is_content_creator                    0
uses_ai_features                      0
daily_notifications                   0
checks_phone_first_morning            0
uses_screen_time_limits               0
dtype: int64

In [35]:
print(df.duplicated().sum())

0

# Task 2: Data Preprocessing

Apply Standardization, Normalization and Encoding.

Apply Standardization

In [7]:
df1 = pd.read_csv("social_media_user_behavior.csv")

df1.head(2)

,user_id,age,age_group,gender,country,occupation,education_level,income_bracket,relationship_status,primary_platform,...,productivity_impact,platform_satisfaction,account_created_date,account_age_years,is_verified_account,is_content_creator,uses_ai_features,daily_notifications,checks_phone_first_morning,uses_screen_time_limits
0,USR-000001,22,18-24,Non-Binary,Philippines,Teacher/Educator,Doctoral/Professional,$100K-$150K,Married,Facebook,...,No Change,Dissatisfied,2025-05-14,0.9,False,False,False,20,True,False
1,USR-000002,31,25-34,Prefer Not to Say,United Kingdom,Marketing Professional,High School or Below,$50K-$75K,In a Relationship,TikTok,...,No Change,Dissatisfied,2019-07-18,6.7,False,False,False,31,True,False

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
lb = LabelEncoder()

In [10]:
df1 = df1.dropna()

In [11]:
df1

,user_id,age,age_group,gender,country,occupation,education_level,income_bracket,relationship_status,primary_platform,...,productivity_impact,platform_satisfaction,account_created_date,account_age_years,is_verified_account,is_content_creator,uses_ai_features,daily_notifications,checks_phone_first_morning,uses_screen_time_limits
0,USR-000001,22,18-24,Non-Binary,Philippines,Teacher/Educator,Doctoral/Professional,$100K-$150K,Married,Facebook,...,No Change,Dissatisfied,2025-05-14,0.9,False,False,False,20,True,False
1,USR-000002,31,25-34,Prefer Not to Say,United Kingdom,Marketing Professional,High School or Below,$50K-$75K,In a Relationship,TikTok,...,No Change,Dissatisfied,2019-07-18,6.7,False,False,False,31,True,False
2,USR-000003,21,18-24,Female,UAE,Legal Professional,High School or Below,$25K-$50K,Single,Instagram,...,Decreased,Neutral,2026-01-10,0.2,False,False,False,47,True,False
3,USR-000004,33,25-34,Female,Saudi Arabia,Unemployed,Some College,$25K-$50K,Single,Instagram,...,Decreased,Neutral,2019-09-28,6.5,False,False,False,28,True,False
4,USR-000005,23,18-24,Female,Poland,Sales Professional,Vocational/Trade,$25K-$50K,It's Complicated,Reddit,...,Increased,Neutral,2022-04-05,4.0,False,True,False,149,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,USR-024996,26,25-34,Male,Bangladesh,Business Owner,High School or Below,$50K-$75K,In a Relationship,TikTok,...,No Change,Neutral,2019-01-27,7.2,False,False,False,77,True,True
24996,USR-024997,29,25-34,Male,Japan,Homemaker,Bachelor's Degree,$25K-$50K,Single,YouTube,...,Decreased,Very Dissatisfied,2011-12-06,14.3,False,False,True,117,False,False
24997,USR-024998,30,25-34,Female,Chile,Retired,Some College,$25K-$50K,In a Relationship,Instagram,...,No Change,Satisfied,2021-02-25,5.1,False,False,False,68,True,True
24998,USR-024999,23,18-24,Female,India,Content Creator/Influencer,Bachelor's Degree,$25K-$50K,In a Relationship,Snapchat,...,Decreased,Very Satisfied,2022-01-31,4.2,False,False,False,29,False,True
24999,USR-025000,39,35-44,Female,Argentina,Government Employee,High School or Below,$50K-$75K,Single,YouTube,...,No Change,Satisfied,2023-05-09,2.9,False,False,False,71,True,False

Categorical To Numerical

In [21]:
df1['productivity_impact'] = lb.fit_transform(df['productivity_impact'])
df1['primary_platform'] = lb.fit_transform(df1['primary_platform'])
df1['platform_satisfaction'] = lb.fit_transform(df1['platform_satisfaction'])
df1['relationship_status'] = lb.fit_transform(df1['relationship_status'])
df1['account_created_date'] = lb.fit_transform(df1['account_created_date'])
df1['income_bracket'] = lb.fit_transform(df1['income_bracket'])
df1['is_verified_account'] = lb.fit_transform(df1['is_verified_account'])
df1['education_level'] = lb.fit_transform(df1['education_level'])
df1['is_content_creator'] = lb.fit_transform(df1['is_content_creator'])
df1['occupation'] = lb.fit_transform(df1['occupation'])
df1['uses_ai_features'] = lb.fit_transform(df1['uses_ai_features'])
df1['country'] = lb.fit_transform(df1['country'])
df1['checks_phone_first_morning'] = lb.fit_transform(df1['checks_phone_first_morning'])
df1['gender'] = lb.fit_transform(df1['gender'])
df1['uses_screen_time_limits'] = lb.fit_transform(df1['uses_screen_time_limits'])
df1['age_group'] = lb.fit_transform(df1['age_group'])
df1['account_age_years'] = lb.fit_transform(df1['account_age_years'])
df1['user_id'] = lb.fit_transform(df1['user_id'])
df1['engagement_rate_pct'] = lb.fit_transform(df1['engagement_rate_pct'])

In [22]:
df1.columns

Index(['user_id', 'age', 'age_group', 'gender', 'country', 'occupation',
       'education_level', 'income_bracket', 'relationship_status',
       'primary_platform', 'num_platforms_used', 'daily_screen_time_minutes',
       'weekly_sessions', 'avg_session_duration_minutes',
       'preferred_content_type', 'primary_device', 'usage_purpose',
       'posts_per_week', 'likes_per_day', 'comments_per_day',
       'shares_per_week', 'followers_count', 'following_count',
       'engagement_rate_pct', 'video_consumption_daily_minutes',
       'has_purchased_via_social', 'follows_influencers', 'ad_click_frequency',
       'monthly_social_spending_usd', 'uses_privacy_settings',
       'experienced_cyberbullying', 'reports_fake_news_frequency',
       'self_reported_mental_health_effect', 'sleep_hours_per_night',
       'addiction_level_1_to_10', 'productivity_impact',
       'platform_satisfaction', 'account_created_date', 'account_age_years',
       'is_verified_account', 'is_content_creator', 'uses_ai_features',
       'daily_notifications', 'checks_phone_first_morning',
       'uses_screen_time_limits'],
      dtype='str')

In [31]:
df['gender'].value_counts()

gender
Female               11930
Male                 11574
Non-Binary            1009
Prefer Not to Say      487
Name: count, dtype: int64

In [34]:
print(df['age'].mean())

34.68384

In [23]:
df1['engagement_rate_pct'].value_counts()

engagement_rate_pct
0      1895
172     138
193     131
165     129
203     124
       ...
553       1
539       1
486       1
541       1
535       1
Name: count, Length: 556, dtype: int64

In [24]:
x = df1.drop(columns= ['country'])
y = df1['country']

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [27]:
from sklearn.preprocessing import StandardScaler

In [28]:
sc = StandardScaler()

In [29]:
x_train_sc = sc.fit_transform(x_train)

ValueError: could not convert string to float: 'Image/Photo'

In [ ]:
x_train_new = pd.DataFrame(x_train_sc , columns=x_train.columns)