In [127]:
import pandas as pd
import numpy as np

In [128]:
from sklearn.linear_model import Ridge , Lasso , ElasticNet
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error , r2_score
from sklearn.preprocessing import StandardScaler

In [129]:
df = pd.read_csv("insurance.csv")
df.head(2)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523

In [130]:
from sklearn.preprocessing import LabelEncoder

In [131]:
lb = LabelEncoder()

In [132]:
df['sex'] = lb.fit_transform(df['sex'])
df['smoker'] = lb.fit_transform(df['smoker'])
df['region'] = lb.fit_transform(df['region'])

In [133]:
df.head()

   age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       3  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       1  21984.47061
4   32    1  28.880         0       0       1   3866.85520

In [134]:
x = df.drop(columns=['charges'])
y=df['charges']

In [135]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state=42)

In [136]:
scalar = StandardScaler()

In [137]:
x_train = scalar.fit_transform(x_train)
x_test = scalar.fit_transform(x_test)

In [138]:
# ## Ridge:::::
# Ridge adds l2 Penatly.
# It reduces Coefficient values but does not make them Exactly

In [139]:
ridge_model = Ridge(alpha=1.0)
ridge_model.fit(x_train, y_train)

Ridge()

In [140]:
ridge_pred = ridge_model.predict(x_test)

In [141]:
ridge_mse = mean_squared_error(y_test , ridge_pred)
ridge_r2 = r2_score(y_test , ridge_pred)
print('MSE: ' ,ridge_mse)
print("R2_Score: ",ridge_r2)
print("\n Cofficients : " , ridge_model.coef_)

MSE:  33644033.32700926
R2_Score:  0.783289480025207

 Cofficients :  [ 3.61244853e+03 -8.73095622e+00  2.02671768e+03  5.16517239e+02
  9.54798452e+03 -3.01857800e+02]

In [142]:
# Lasso adds L1 Penalty 
# It Can Make Some Coefficients Exactly Zero To Performs Feature Selection

In [143]:
lasso_model = Lasso(alpha=0.1)
lasso_model.fit(x_train , y_train)

Lasso(alpha=0.1)

In [144]:
lasso_pred = lasso_model.predict(x_test)

In [145]:
lasso_mse = mean_squared_error(y_test , lasso_pred)
lasso_r2 = r2_score(y_test , lasso_pred)

print("Mse: ", lasso_mse)
print("r2_score: ", lasso_r2)
print("\n Cofficient " , lasso_model.coef_)

Mse:  33638971.48321596
r2_score:  0.7833220847604899

 Cofficient  [ 3.61602151e+03 -9.28056722e+00  2.02819649e+03  5.16568126e+02
  9.55703303e+03 -3.02268134e+02]

In [146]:
# ## ElasticNet combines both:
# l1 Regularization (Lasso)
# l2 Regularization (Ridge)

In [147]:
elasticnet_model = ElasticNet(alpha=0.1 , l1_ratio=0.5)
elasticnet_model.fit(x_train , y_train)

ElasticNet(alpha=0.1)

In [148]:
elasticnet_pred = elasticnet_model.predict(x_test)

In [149]:
elasticnet_mse = mean_squared_error(y_test , elasticnet_pred)
elasticnet_r2 = r2_score(y_test , elasticnet_pred)

print("Mse: " ,elasticnet_mse)
print("r2_score: ", elasticnet_r2)

print("\n Conficient : ", elasticnet_model.coef_)

Mse:  34180040.177204974
r2_score:  0.7798369117172713

 Conficient :  [3430.23775281   22.74438893 1946.4078572   508.36314547 9090.70832049
 -275.8133229 ]

In [150]:
# Cross Validation

In [151]:
from sklearn.linear_model import LassoCV
lasso_cv= LassoCV(
    alphas=[0.001 , 0.01 , 0.1 , 1 , 10],
    cv=5,
    random_state=42
)

lasso_cv.fit(x_train ,y_train)
print("Best Alpha : " , lasso_cv.alpha_)

Best Alpha :  10.0

In [152]:
from sklearn.linear_model import ElasticNetCV

elasticnet_cv = ElasticNetCV(
    l1_ratio=[0.1 , 0.3 , 0.5 , 0.7 , 0.9 , 1],
    alphas=[0.001 , 0.01 , 0.1 , 1 ,10],
    cv = 5,
    random_state=42
    
)

elasticnet_cv.fit(x_train , y_train)
print("Best Alpha: ", elasticnet_cv.alpha_)
print("Best l1_ratio: ", elasticnet_cv.l1_ratio_)

Best Alpha:  10.0
Best l1_ratio:  1.0