In [29]:
print("Hello World")

Hello World

In [45]:
import pandas as pd

### pip install pandas

In [46]:
import mysql.connector
### pip install mysql-connector-python

In [58]:
# conn = mysql.connector.connect(host = 'localhost',
#                                user ='root',
#                                password='1234',
#                                database='world')

# Import Module

In [47]:
from sqlalchemy import create_engine

### pip install SQLAlchemy

In [49]:
engine = create_engine('mysql+mysqlconnector://root:1234@localhost/world')

In [50]:
query  = "select * from city"

In [51]:
df = pd.read_sql(query , engine)

In [52]:
df

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]

# Append The Data in The SQL

In [55]:
data = [('Devendra','Ind','Jaipur','123432400')]

df_new = pd.DataFrame(data,columns=['Name','CountryCode','District','Population'])
df_new

       Name CountryCode District Population
0  Devendra         Ind   Jaipur  123432400

In [57]:
df_new.to_sql('city',engine,if_exists='append',index=False)

1