In [27]:
print("Hello World")

Hello World

In [28]:
import numpy as np 
import pandas as pd

In [29]:
df = pd.read_csv("insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [30]:
from sklearn.preprocessing import LabelEncoder

In [31]:
lb = LabelEncoder()

In [32]:
df['sex'] = lb.fit_transform(df['sex'])
df['smoker'] = lb.fit_transform(df['smoker'])
df['region'] = lb.fit_transform(df['region'])

In [33]:
df.head(2)

   age  sex    bmi  children  smoker  region     charges
0   19    0  27.90         0       1       3  16884.9240
1   18    1  33.77         1       0       2   1725.5523

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
x = df.drop(columns=['bmi'])
y=df['bmi']

In [36]:
x_train , x_test ,y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state=42)

In [37]:
from sklearn.preprocessing import StandardScaler

In [38]:
sc=StandardScaler()

In [39]:
x_train_sc =sc.fit_transform(x_train)

In [40]:
x_train_new = pd.DataFrame(x_train_sc)

In [41]:
np.round(x_train_new.describe(),2)

             0        1        2        3        4        5
count  1070.00  1070.00  1070.00  1070.00  1070.00  1070.00
mean     -0.00    -0.00    -0.00     0.00    -0.00     0.00
std       1.00     1.00     1.00     1.00     1.00     1.00
min      -1.52    -1.02    -0.91    -0.51    -1.35    -1.02
25%      -0.88    -1.02    -0.91    -0.51    -0.46    -0.70
50%       0.01     0.98    -0.09    -0.51     0.44    -0.31
75%       0.83     0.98     0.73    -0.51     0.44     0.28
max       1.75     0.98     3.20     1.97     1.34     4.10