In [149]:
import numpy as np
import pandas as pd

In [150]:
df = pd.read_csv('tips.csv')
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [151]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [152]:
from sklearn.preprocessing import LabelEncoder

In [153]:
lb =LabelEncoder()

In [154]:
df['sex'] = lb.fit_transform(df['sex'])
df['smoker'] = lb.fit_transform(df['smoker'])
df['day'] = lb.fit_transform(df['day'])
df['time'] = lb.fit_transform(df['time'])

In [155]:
x = df.drop(columns=['total_bill'])
y =df['total_bill']

In [156]:
from sklearn.model_selection import train_test_split

In [157]:
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size=0.2 , random_state=42)

In [161]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

In [162]:
transformer = ColumnTransformer(transformers=[
    ('tnf1' ,SimpleImputer(),['sex'])
],remainder='passthrough')

In [164]:
transformer.fit_transform(x_train).shape

(195, 6)

In [165]:
df = pd.read_csv('tips.csv')
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [177]:
a = pd.get_dummies(df , columns=['sex','smoker','day','time'],drop_first=True)

In [178]:
a.astype(int)

,total_bill,tip,size,sex_Male,smoker_Yes,day_Sat,day_Sun,day_Thur,time_Lunch
0,16,1,2,0,0,0,1,0,0
1,10,1,3,1,0,0,1,0,0
2,21,3,3,1,0,0,1,0,0
3,23,3,2,1,0,0,1,0,0
4,24,3,4,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...
239,29,5,3,1,0,1,0,0,0
240,27,2,2,0,1,1,0,0,0
241,22,2,2,1,1,1,0,0,0
242,17,1,2,1,0,1,0,0,0
243,18,3,2,0,0,0,0,1,0

In [166]:
from sklearn.preprocessing import OneHotEncoder

In [167]:
ohe = OneHotEncoder(sparse_output=False , drop='first')

In [179]:
a = ohe.fit_transform(df[['sex' ,'smoker' , 'day' , 'time']])
a

array([[0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       ...,
       [1., 1., 1., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.]], shape=(244, 6))

In [170]:
pd.DataFrame(a)

       0    1    2    3    4    5
0    0.0  0.0  0.0  1.0  0.0  0.0
1    1.0  0.0  0.0  1.0  0.0  0.0
2    1.0  0.0  0.0  1.0  0.0  0.0
3    1.0  0.0  0.0  1.0  0.0  0.0
4    0.0  0.0  0.0  1.0  0.0  0.0
..   ...  ...  ...  ...  ...  ...
239  1.0  0.0  1.0  0.0  0.0  0.0
240  0.0  1.0  1.0  0.0  0.0  0.0
241  1.0  1.0  1.0  0.0  0.0  0.0
242  1.0  0.0  1.0  0.0  0.0  0.0
243  0.0  0.0  0.0  0.0  1.0  0.0

[244 rows x 6 columns]