In [29]:
print("Get Dummies And OneHotEncoder")

Get Dummies And OneHotEncoder

Q1. What is Feature Engeneering ?.

Ans: in Feature Engeneeriung we basically create more features or reduce features on the basics of our requirnment.

In [30]:
import numpy as np

In [31]:
data = {
    'Name':['Rahul','Ram','Shyam'],
    'City': ['Dehli','Jaipur','Bhratpur']
}

In [32]:
import pandas as pd

In [33]:
df = pd.DataFrame(data)
df

    Name      City
0  Rahul     Dehli
1    Ram    Jaipur
2  Shyam  Bhratpur

By Usign the Pandas get_dummies Method

In [34]:
get_dummies_01 = pd.get_dummies(df['City'] , dtype=int)
get_dummies_01

   Bhratpur  Dehli  Jaipur
0         0      1       0
1         0      0       1
2         1      0       0

By Usign The Skite-Learn OneHotEncoding mehtod

In [35]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output=False)

In [37]:
d = ohe.fit_transform(df[['City']] , columns = ohe.get_feature_names_out())

NotFittedError: This OneHotEncoder instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.