In [29]:
print("Get Dummies And OneHotEncoder")

Get Dummies And OneHotEncoder

Q1. What is Feature Engeneering ?.

Ans: in Feature Engeneeriung we basically create more features or reduce features on the basics of our requirnment.

Ml PipLines: 

* Data --> 
* Preprocessing --> 
* Eda (univirate , Bivariate , Multivirate) --> 
* Feature Eng & Selection (Feature Scaling ) --> 
* Model Selection --> 
* Model Training --> 
* Model Evaluation

                                                        Features 
                                                            |
                                                    |                       |
                                                Numerical              categorical
                                                    |                       |
                                        |               |              |                |
                                    Discreate        Contiuious     Nominal           Ordinal

In [30]:
import numpy as np

In [31]:
data = {
    'Name':['Rahul','Ram','Shyam'],
    'City': ['Dehli','Jaipur','Bhratpur']
}

In [32]:
import pandas as pd

In [33]:
df = pd.DataFrame(data)
df

    Name      City
0  Rahul     Dehli
1    Ram    Jaipur
2  Shyam  Bhratpur

By Usign the Pandas get_dummies Method

In [34]:
get_dummies_01 = pd.get_dummies(df['City'] , dtype=int)
get_dummies_01

   Bhratpur  Dehli  Jaipur
0         0      1       0
1         0      0       1
2         1      0       0

By Usign The Skite-Learn OneHotEncoding mehtod

Step 1 : First We import OneHotEncoder from the Skite-Learn

In [35]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output=False)

Step 2 : fit_transform :  That Means Lean And Apply

In [38]:
d = ohe.fit_transform(df[['City']])

In [44]:
#  Step 3 :  Convert Into the DataFrmae

get_feature_names_out() : Are used to view the columns name

In [43]:
# Convert Into The DataFrame
Ohe_DataFrmae = pd.DataFrame(d , columns= ohe.get_feature_names_out())
Ohe_DataFrmae

   City_Bhratpur  City_Dehli  City_Jaipur
0            0.0         1.0          0.0
1            0.0         0.0          1.0
2            1.0         0.0          0.0