In [47]:
print("Pratice : Numpy , Pandas, Get_dummies , OneHotEncoder , LabelEncoder , OrdinalEncoder ")

Pratice : Numpy , Pandas, Get_dummies , OneHotEncoder , LabelEncoder , OrdinalEncoder

In [48]:
import pandas as pd
import numpy as np

In [49]:
df = pd.read_csv("covid_toy.csv")
df.sample()

   age  gender  fever cough   city has_covid
9   64  Female  101.0  Mild  Delhi        No

In [50]:
df.shape

(100, 6)

In [51]:
df.size

600

In [52]:
df.columns

Index(['age', 'gender', 'fever', 'cough', 'city', 'has_covid'], dtype='str')

In [53]:
cat_col = df.select_dtypes(include=['str' , 'object']).columns
cat_col

Index(['gender', 'cough', 'city', 'has_covid'], dtype='str')

In [54]:
num_col = df.select_dtypes(include=['int64','float64']).columns
num_col

Index(['age', 'fever'], dtype='str')

In [55]:
get_dummies_d = pd.get_dummies(df , dtype=int)
get_dummies_d

,age,fever,gender_Female,gender_Male,cough_Mild,cough_Strong,city_Bangalore,city_Delhi,city_Kolkata,city_Mumbai,has_covid_No,has_covid_Yes
0,60,103.0,0,1,1,0,0,0,1,0,1,0
1,27,100.0,0,1,1,0,0,1,0,0,0,1
2,42,101.0,0,1,1,0,0,1,0,0,1,0
3,31,98.0,1,0,1,0,0,0,1,0,1,0
4,65,101.0,1,0,1,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
95,12,104.0,1,0,1,0,1,0,0,0,1,0
96,51,101.0,1,0,0,1,0,0,1,0,0,1
97,20,101.0,1,0,1,0,1,0,0,0,1,0
98,5,98.0,1,0,0,1,0,0,0,1,1,0
99,10,98.0,1,0,0,1,0,0,1,0,0,1

In [56]:
from sklearn.preprocessing import OneHotEncoder

In [57]:
ohe = OneHotEncoder(sparse_output=False , drop='first')

In [58]:
ohe_d = ohe.fit_transform(df)
ohe_d

ohe_df = pd.DataFrame(ohe_d , columns=ohe.get_feature_names_out())
ohe_df

,age_6,age_8,age_10,age_11,age_12,age_13,age_14,age_15,age_16,age_17,...,fever_101.0,fever_102.0,fever_103.0,fever_104.0,fever_nan,cough_Strong,city_Delhi,city_Kolkata,city_Mumbai,has_covid_Yes
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
96,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
97,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
98,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
99,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0